#!/usr/bin/env bash
# Script that configures an Nginx server to listen on port 80

sudo apt-get -y update
sudo apt-get install -y nginx

sudo nginx -t
exit_code=$?

if (( exit_code == 0))
then
	sudo service nginx restart
fi
