#!/usr/bin/env bash
# Script that configures an Nginx server in few lines
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx reload
