#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100
# Displays FizzBuzz when number is a multiple of 3 and 5
# Displays Fizz when number is a multiple of 3
# Displays Buzz when number is a multiple of 5

i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
