#!/usr/bin/env bash
# This script is displaying the content of the current directory
# in a list format
# where only the part of the name after the first dash is displayed

for i in *
do
	echo "${i//[0-9]*-/}"
done
