#!/usr/bin/env bash
# This script is giving information about the school file

s_file="school"
if [ -e "$s_file" ]
then
	echo "$s_file file exists"
	if [ -s "$s_file" ]
	then
		echo "$s_file file is not empty"
	else
		echo "$s_file file is empty"
	fi
	if [ -f "$s_file" ]
	then
		echo "$s_file is a regular file"
	fi
else
	echo "$s_file file does not exist"
fi
