#!/usr/bin/env bash
# Script that configures an Nginx server to listen on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo nginx -t
exit_code=$?

if (( exit_code == 0))
then
	sudo service nginx restart
fi
