#!/usr/bin/env bash
# Script configures nginx server to run as nginx user and listen on port 8080
sed -i "s/^#\?user .*/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/\<80\>/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx restart
