#!/usr/bin/env bash
# Script to reload Gunicorn in a graceful way

pgrep -f gunicorn | while read -r pid
do
	if [ "$(ps -o ppid= -p "$pid" | awk '{ print $1 }')" -eq 1 ]
	then
		kill -SIGHUP "$pid"
	fi
done
